-- DB model V2

create sequence OPPONENT_SEQU;
create sequence GAME_SEQU;
create sequence TURN_SEQU;
create sequence SET_SEQU;

-------------

CREATE TABLE opponent
(
OpponentID bigint GENERATED BY DEFAULT AS SEQUENCE OPPONENT_SEQU PRIMARY KEY,
OpponentName varchar(128) NOT NULL
);

CREATE TABLE game
(
GameID bigint GENERATED BY DEFAULT AS SEQUENCE GAME_SEQU PRIMARY KEY,
OpponentID int not null,
PlayTime TIMESTAMP default CURRENT_TIMESTAMP,
PointsOwn int,
PointsOpponent int,
Winner varchar(1),
FOREIGN KEY (OpponentID) REFERENCES opponent(OpponentID)
);

CREATE TABLE gameset
(
SetID bigint GENERATED BY DEFAULT AS SEQUENCE SET_SEQU PRIMARY KEY,
GameID int not null,
StartingPlayer varchar(1) not null,
Winner varchar(1),
PointsOwnBeforeSet int not null,
PointsOpponentBeforeSet int not null,
FOREIGN KEY (GameID) REFERENCES game(GameID)
);

CREATE TABLE turn
(
TurnID bigint GENERATED BY DEFAULT AS SEQUENCE TURN_SEQU PRIMARY KEY,
GameID int not null,
SetID int not null,
Turn varchar(1) not null,
Column int not null,
FOREIGN KEY (GameID) REFERENCES game(GameID),
FOREIGN KEY (SetID) REFERENCES gameset(SetID)
);